import { Toaster } from "@/components/ui/toaster";
import { getPermissionsFromToken } from "@/lib/permission-utils";
import { getSession } from "@/lib/session";
import { AuthProvider } from "@/providers/auth-provider";
import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const permissions = getPermissionsFromToken(session);

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${outfit.variable} ${inter.variable} antialiased font-sans`}
      >
        <AuthProvider initialPermissions={permissions}>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
