-- AlterTable
ALTER TABLE "Coupon" ALTER COLUMN "discountValue" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "minOrderAmount" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "maxDiscountAmount" SET DATA TYPE DECIMAL(20,2);

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "totalAmount" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "shippingFee" SET DATA TYPE DECIMAL(20,2);

-- AlterTable
ALTER TABLE "OrderItem" ALTER COLUMN "priceAtPurchase" SET DATA TYPE DECIMAL(20,2);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "maxPrice" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "minPrice" SET DATA TYPE DECIMAL(20,2);

-- AlterTable
ALTER TABLE "Sku" ALTER COLUMN "price" SET DATA TYPE DECIMAL(20,2),
ALTER COLUMN "salePrice" SET DATA TYPE DECIMAL(20,2);
